routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::group(['middleware'=>['auth']],function() {
    Route::get('/', function () {
        return view('panel.pages.dashboard');
    })->name('showDashboard');
});
*/

Route::group(['middleware'=>['auth','init_shared_data']],function() {
	Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('showDashboard');
});

Auth::routes(['register' => false]);

Route::group(['middleware'=>['auth','init_shared_data']],function() {
	Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
});


Route::get('products/update-all', [\App\Http\Controllers\Admin\ProductController::class, 'updateAllProducts'])->name('products.updateAllProducts');

Route::get('customers/update-all', [\App\Http\Controllers\Admin\CustomerController::class, 'updateAllCustomers'])->name('customers.updateAllCustomers');


Route::group(['middleware' => ['auth', 'init_shared_data']], function() {
	
	
	Route::get('users/toggle-walking-status', [\App\Http\Controllers\Admin\UserController::class, 'toggleWalkingStatus'])->name('users.toggleWalkingStatus');
	
	Route::get('users/{user_id}/geo-update', [\App\Http\Controllers\Admin\UserController::class, 'updateGeoPath'])->name('users.updateGeoPath');
	Route::get('users/{user_id}/walked-paths', [\App\Http\Controllers\Admin\UserController::class, 'showUserWalkedPaths'])->name('users.showUserWalkedPaths');
	
	Route::get('users/{path_id}/show-walked-path', [\App\Http\Controllers\Admin\UserController::class, 'showWalkedPath'])->name('users.showWalkedPath');
	
	
	Route::get('clues/report', [\App\Http\Controllers\Admin\ClueController::class, 'showCluesReport'])->name('clues.showCluesReport');
	
	Route::post('clues/merge', [\App\Http\Controllers\Admin\ClueController::class, 'mergeToAnotherClue'])->name('clues.merge');
	
	Route::post('clues/merge/confirm', [\App\Http\Controllers\Admin\ClueController::class, 'mergeConfirmToAnotherClue'])->name('clues.merge.confirm');
	
	Route::get('clues/{clue_id}/cartable', [\App\Http\Controllers\Admin\ClueController::class, 'showCartable'])->name('clues.showCartable');
	Route::post('clues/add-new-note', [\App\Http\Controllers\Admin\ClueController::class, 'addNewNote'])->name('clues.addNewNote');
	Route::post('clues/add-new-report-process', [\App\Http\Controllers\Admin\ClueController::class, 'addNewReportProcess'])->name('clues.addNewReportProcess');
	Route::post('clues/update-clue-customer-status', [\App\Http\Controllers\Admin\ClueController::class, 'updateClueCustomerStatus'])->name('clues.updateClueCustomerStatus');
	Route::post('clues/update-clue-business-status', [\App\Http\Controllers\Admin\ClueController::class, 'updateClueBusinessStatus'])->name('clues.updateClueBusinessStatus');
	Route::post('clues/update-clue-pre-invoice-status', [\App\Http\Controllers\Admin\ClueController::class, 'updateCluePreInvoiceStatus'])->name('clues.updateCluePreInvoiceStatus');
	Route::post('clues/update-clue-invoice-status', [\App\Http\Controllers\Admin\ClueController::class, 'updateClueInvoiceStatus'])->name('clues.updateClueInvoiceStatus');
	
	
	Route::post('clues/update-clue-description', [\App\Http\Controllers\Admin\ClueController::class, 'updateClueDescription'])->name('clues.updateClueDescription');
	
	
	Route::post('clues/update-clue-products', [\App\Http\Controllers\Admin\ClueController::class, 'updateClueProducts'])->name('clues.updateClueProducts');
	
	Route::post('clues/update-clue-marketing-list', [\App\Http\Controllers\Admin\ClueController::class, 'updateClueMarketingList'])->name('clues.updateClueMarketingList');
	
	
	
	
	Route::resource('clues', \App\Http\Controllers\Admin\ClueController::class);
	
	
	Route::get('competitors/report', [\App\Http\Controllers\Admin\CompetitorController::class, 'showCompetitorsReport'])->name('competitors.showCompetitorsReport');
	
	Route::resource('competitors', \App\Http\Controllers\Admin\CompetitorController::class);
	
	 
	

    Route::resource('roles', \App\Http\Controllers\Admin\RoleController::class);
    
    Route::get('users/cities/edit/{user_id}', [\App\Http\Controllers\Admin\UserController::class, 'editUserCities'])->name('users.edit-user-cities');
    Route::get('users/cities/add', [\App\Http\Controllers\Admin\UserController::class, 'addCityToUser'])->name('users.add-city-to-user');
    Route::delete('users/cities/remove', [\App\Http\Controllers\Admin\UserController::class, 'removeUserCity'])->name('users.remove-user-city');
    Route::delete('users/cities/remove-mass', [\App\Http\Controllers\Admin\UserController::class, 'removeUserCityMass'])->name('users.remove-user-city-mass');

    Route::resource('users', \App\Http\Controllers\Admin\UserController::class);
    
    
	Route::get('campaigns/{campaign_id}/report', [\App\Http\Controllers\Admin\CampaignController::class, 'showCampaignReport'])->name('campaigns.showCampaignsReport');
	Route::resource('campaigns', \App\Http\Controllers\Admin\CampaignController::class);
	
	
    Route::resource('products', \App\Http\Controllers\Admin\ProductController::class);

	Route::get('business/{business_id}/cartable', [\App\Http\Controllers\Admin\BusinessController::class, 'showCartable'])->name('businesses.showCartable');
	
	
	Route::get('business/brands/edit/{business_id}', [\App\Http\Controllers\Admin\BrandController::class, 'editBusinessBrands'])->name('brands.editBusinessBrands');
	Route::patch('business/brands/update', [\App\Http\Controllers\Admin\BrandController::class, 'updateBusinessBrands'])->name('brands.updateBusinessBrands');
	
	
	//Route::get('business/brands/show/{business_id}', [\App\Http\Controllers\Admin\BrandController::class, 'showBusinessBrands'])->name('brands.showBusinessBrands');
	
	
	Route::resource('brands', \App\Http\Controllers\Admin\BrandController::class);
	
	Route::resource('proceedings', \App\Http\Controllers\Admin\ProceedingController::class);
	
	Route::resource('marketing', \App\Http\Controllers\Admin\MarketingController::class);
    
	Route::get('configs/edit', [\App\Http\Controllers\Admin\ConfigController::class, 'edit'])->name('configs.edit');
    Route::post('configs/update', [\App\Http\Controllers\Admin\ConfigController::class, 'update'])->name('configs.update');
    
	Route::get('teams/members/{team_id}', [\App\Http\Controllers\Admin\TeamController::class, 'createTeamMembers'])->name('teams.show-createTeamMembers-form');
	Route::post('teams/members/store-team-members', [\App\Http\Controllers\Admin\TeamController::class, 'storeTeamMembers'])->name('teams.store-team-members');
    
	Route::get('teams/report/{team_id}', [\App\Http\Controllers\Admin\TeamController::class, 'showTeamReport'])->name('teams.show-team-report'); 
	
    Route::resource('teams', \App\Http\Controllers\Admin\TeamController::class);
	
	Route::get('businesses/report', [\App\Http\Controllers\Admin\BusinessController::class, 'showBusinessesReport'])->name('businesses.showBusinessesReport');

    Route::resource('businesses', \App\Http\Controllers\Admin\BusinessController::class);
    
    Route::post('businesses/add-new-note', [\App\Http\Controllers\Admin\BusinessController::class, 'addNewNote'])->name('businesses.addNewNote');
    
    Route::get('accountant/business/approve/{business_id}', [\App\Http\Controllers\Admin\BusinessController::class, 'showAccountantApprovingForm'])->name('business.show-accounting-approving-form');
    
    Route::post('accountant/business/approve/{business_id}', [\App\Http\Controllers\Admin\BusinessController::class, 'accountantApprovingBusiness'])->name('business.accounting-approving-business');
    
    Route::get('sales-specialist/business/approve/{business_id}', [\App\Http\Controllers\Admin\BusinessController::class, 'showSalesSpecialistApprovingForm'])->name('business.show-sales-specialist-approving-form');
    
    Route::post('sales-specialist/business/approve/{business_id}', [\App\Http\Controllers\Admin\BusinessController::class, 'salesSpecialistApprovingBusiness'])->name('business.sales-specialist-approving-business');

    Route::resource('cities', \App\Http\Controllers\Admin\CityController::class);


    Route::get('comments/report', [\App\Http\Controllers\Admin\CommentController::class, 'showCommentsReport'])->name('comments.showCommentsReport');

    Route::resource('comments', \App\Http\Controllers\Admin\CommentController::class);
    
    
    Route::get('customers/{customer_id}/cartable', [\App\Http\Controllers\Admin\CustomerController::class, 'showCartable'])->name('customers.showCartable');
   
	Route::get('customers/report', [\App\Http\Controllers\Admin\CustomerController::class, 'showCustomersReport'])->name('customers.showCustomersReport');

    Route::resource('customers', \App\Http\Controllers\Admin\CustomerController::class);
    
    

    Route::get('sms/history', [\App\Http\Controllers\Admin\SmsController::class, 'history'])->name('sms.history');
    Route::get('sms/send/send-specialist-info', [\App\Http\Controllers\Admin\SmsController::class, 'sendSpecialistInfo'])->name('sms.sendSpecialistInfo');
    Route::get('sms/send', [\App\Http\Controllers\Admin\SmsController::class, 'showSendForm'])->name('sms.showSendForm');
    Route::post('sms/send', [\App\Http\Controllers\Admin\SmsController::class, 'sendSMS'])->name('sms.sendSMS');
    
    //Route::resource('sms', \App\Http\Controllers\Admin\SmsController::class);
    
    Route::post('customers/upload-excel-file', [\App\Http\Controllers\Admin\CustomerController::class, 'uploadExcelFile'])->name('customers.uploadExcelFile');
    

app/Models/User.php
<?php



namespace App\Models;



use Illuminate\Contracts\Auth\MustVerifyEmail;

use Illuminate\Database\Eloquent\Factories\HasFactory;

use Illuminate\Foundation\Auth\User as Authenticatable;

use Illuminate\Notifications\Notifiable;

use Spatie\Permission\Traits\HasRoles;



class User extends Authenticatable

{

    use HasFactory, Notifiable, HasRoles;



    /**

     * The attributes that are mass assignable.

     *

     * @var array

     */

    protected $fillable = [

        'name',

        'email',

        'password',

        'user_type',
		
        'allowed_daily_walkings_count',
		
        'is_active',

    ];



    /**

     * The attributes that should be hidden for arrays.

     *

     * @var array

     */

    protected $hidden = [

        'password',

        'remember_token',

    ];



    /**

     * The attributes that should be cast to native types.

     *

     * @var array

     */

    protected $casts = [

        'email_verified_at' => 'datetime',

    ];


    public function cities()
    {
        return $this->belongsToMany(City::class,'users_cities','user_id','city_id');
    }


    public function subUsers()
    {
        return $this->hasMany(User::class,'parent_user_id','id');
    }

}

resources/views/panel/admin/users/create.blade.php
@extends('panel.layout.master')
@section('main_content')

    <div class="row mb-md-5">

        <div class="col-lg-12 margin-tb">

            <div class="pull-right">

                <h2>ایجاد کاربر جدید</h2>

            </div>

            <div class="pull-left">

                <a class="btn btn-primary" href="{{ route('users.index') }}"> بازگشت</a>

            </div>

        </div>

    </div>


    @if (count($errors) > 0)

        <div class="alert alert-danger">

            <strong>خطا!</strong> در مقادیر ورودی ایراداتی وجود دارد.<br><br>

            <ul>

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif



    {!! Form::open(array('route' => 'users.store','method'=>'POST')) !!}

    <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>نام و نام خانوادگی:</strong>

                {!! Form::text('name', null, array('placeholder' => '','class' => 'form-control')) !!}

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>ایمیل:</strong>

                {!! Form::text('email', null, array('placeholder' => '','class' => 'form-control')) !!}

            </div>

        </div>


        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>نوع کاربر:</strong>
                {!! Form::select('user_type', ['ADMIN'=>'ADMIN','CSO'=>'CSO','SALES_MANAGER'=>'SALES_MANAGER','SALES_SPECIALIST'=>'SALES_SPECIALIST','SALES_ACCOUNTANT'=>'SALES_ACCOUNTANT'
                ,'STOCK'=>'STOCK','DRIVER'=>'DRIVER'],[], array('class' => 'form-control')) !!}

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>رمز عبور:</strong>

                {!! Form::password('password', array('placeholder' => '','class' => 'form-control')) !!}

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>تکرار رمز عبور:</strong>

                {!! Form::password('confirm-password', array('placeholder' => '','class' => 'form-control')) !!}

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>نقش ها:</strong>

                {!! Form::select('roles[]', $roles,[], array('class' => 'form-control','multiple')) !!}

            </div>

        </div>
		
		
		 <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>شماره VOIP:</strong>

                {!! Form::text('voip_id', null, array('placeholder' => '','class' => 'form-control')) !!}

            </div>

        </div>
		
		
		<div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>وضعیت:</strong>
                {!! Form::select('is_active', ['1'=>'فعال','0'=>'غیرفعال'],[], array('class' => 'form-control')) !!}

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12 text-center">

            <button type="submit" class="btn btn-primary">ثبت</button>

        </div>

    </div>

    {!! Form::close() !!}



@endsection

resources/views/panel/admin/users/edit-user-cities.blade.php
@extends('panel.layout.master')
@section('additional_css')

<style>
	
	.region-card{
		cursor: pointer;
	}
	
	.region-card.checked{
		right: -3px;
		left: -3px;
		width: calc(100% + 6px);
		top: -3px;
		bottom: -3px;
		height: calc(94%);
		background-color: #e6e6e6;
	}
	
</style>

@endsection
@section('main_content')

	


    <div class="row mb-md-5">

        <div class="col-lg-12 margin-tb">

            <div class="pull-right">

                <h2>ویرایش دسترسی مناطق برای کاربر: {{$user->name}}</h2>

            </div>

            <div class="pull-left">

                <a class="btn btn-primary" href="{{ route('users.index') }}"> بازگشت</a>

            </div>

        </div>

    </div>


    @if (count($errors) > 0)

        <div class="alert alert-danger">

            <strong>خطا!</strong> در مقادیر ورودی ایراداتی وجود دارد.<br><br>

            <ul>

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif
    
    
    @if ($message = Session::get('success'))

        <div class="alert alert-success">

            <p>{{ $message }}</p>

        </div>

    @endif
    
    @if ($message = Session::get('danger'))

        <div class="alert alert-danger">

            <p>{{ $message }}</p>

        </div>

    @endif
    
    
    
    
    
    <div class="row">    
    <div class="col-lg-12 mb-md-5">
        <form action="{{route('users.add-city-to-user')}}" method="GET">
        
        
        <input type="hidden" name="user_id" value="{{$user->id}}">
        
        <div class="row">
	    
	    
	    
	    
	    
	    
	    <div class="col-xs-12 col-sm-12 col-md-3 form-input-container">

                <div class="form-group">

                    <strong>استان(*):</strong>

                    <select required  name='state_id' id='state_id' class='form-control pull-right' onChange="change_list('state_id','city_id','loading_gif_cities','{{route('getCities')}}',['region_id'])"> 				<!-- TODO: init vars -->
                        <option {{(!old('state_id', isset($business->state_id) ? $business->state_id : '')? 'selected' : '')}} value="">انتخاب کنید</option>
                        @foreach($states as $state)
                            <option @if(old('state_id', isset($business->state_id) ? $business->state_id : '')==$state->id) selected @endif value="{{$state->id}}" >{{$state->unit_name}}</option>
                        @endforeach
                    </select>

                </div>

            </div>



            <div class="col-xs-12 col-sm-12 col-md-3 form-input-container">

                <div class="form-group">

                    <strong>شهر:</strong>

                    <select  name='city_id' id='city_id' class='form-control pull-right' onChange="change_list('city_id','region_id','loading_gif_regions','{{route('getCities')}}')">
                        @if($cities)
                            <option {{(!old('city_id', isset($business->city_id) ? $business->city_id : '')? 'selected' : '')}} value="">انتخاب کنید</option>
                            @foreach($cities as $city)
                                <option @if(old('city_id', isset($business->city_id) ? $business->city_id : '')==$city->id) selected @endif value="{{$city->id}}" >{{$city->unit_name}}</option>
                            @endforeach
                        @endif
                    </select>

                </div>

            </div>


            <div class="col-xs-12 col-sm-12 col-md-3 form-input-container">

                <div class="form-group">

                    <strong>منطقه:</strong>

                    <select  name='region_id' id='region_id' class='form-control pull-right'>
                        @if($regions)
                            <option {{(!old('region_id', isset($business->region_id) ? $business->region_id : '')? 'selected' : '')}} value="">انتخاب کنید</option>
                            @foreach($regions as $region)
                                <option @if(old('region_id', isset($business->region_id) ? $business->region_id : '')==$region->id) selected @endif value="{{$region->id}}" >{{$region->unit_name}}</option>
                            @endforeach
                        @endif
                    </select>

                </div>

            </div>
            
            
            <div class="col-xs-12 col-sm-12 col-md-2 form-input-container">

                <div class="form-group">

                    <strong>&nbsp;</strong>

                    <button type="submit" class="btn btn-success" href="{{ route('users.add-city-to-user') }}">افزودن</button>

                </div>

            </div>
	    
	    
	    
	    
	    
	    

	
	
        </div>
        

        </form>
    </div>
</div>
    
    
    
    
    
    
    
    
    


    <div class="row">
    
    
    	@foreach($userRegions as $userRegion)
    	
    		<div class="col-xs-12 col-sm-12 col-md-3">
    		
    		
			<div class="card region-card" onclick="toggleRegionCard(this)">
			  <div class="card-body">
			  
				<div class="float-right">

					<p>{{$userRegion->unit_name}}</p>
					
					@php
					$city = $userRegion->parent()->first();
					$state = $city->parent()->first();
					@endphp
    					<p class="card-subtitle mb-2 text-muted">
    					
    					{{$city->unit_name}} - {{$state->unit_name}}
    					
    					</p>

					

				</div>

				<div class="float-left">
				

					<form action="{{ route('users.remove-user-city') }}" method="POST">

						<input type="hidden" name="user_id" value="{{$user->id}}">
						<input type="hidden" name="region_id" value="{{$userRegion->id}}">

						@csrf

						@method('DELETE')

						

					    <button type="submit" class="btn btn-sm btn-danger">حذف</button>
						
						
						<div class="form-check-inline">
						  <label class="form-check-label">
							<input type="checkbox" form="massDeletionForm" class="form-check-input region-card-checkbox hide" name="region_id[]" value="{{$userRegion->id}}">
						  </label>
						</div>

						
					</form>
				
				</div>
			  
			  
			  </div>
			</div>
    		

		    

		</div>
    	
    	@endforeach

        



    </div>


	<div class="row mt-5">
		<div class="col-xs-12 col-sm-12 col-md-3">
			<form id="massDeletionForm" action="{{ route('users.remove-user-city-mass') }}" method="POST">
			
				@method('DELETE')
			
				{!! csrf_field() !!}
				
				<input type="hidden" name="user_id" value="{{$user->id}}">
			
				<button type="submit" class="btn btn-danger">حذف چندتایی</button>
			
			</form>
		</div>
	</div>


@endsection

@section('additional_js_bottom')


<script>




function change_list(master_el_id,child_el_id,loading_gif_id,ajax_req_url,depend_element_ids = []){

    var e = document.getElementById(master_el_id);
    r_id = e.options[e.selectedIndex].value;

    if(r_id==""){
        $('#'+child_el_id).html('');
        return;
    }

    $('#'+master_el_id).prop('disabled', true);
    //$('#'+loading_gif_id).css('display', 'block'); //TODO: enable loadings

    token= $('body').find("input[name='_token']").val();

    $.ajax({
        url: ajax_req_url,
        type: 'GET',
        data: {"r_id":r_id, "_token":token },
        success: function(data){

            $('#'+child_el_id).html('');
            html_str='<option value="" >انتخاب کنید</option>';
            $('#'+child_el_id).append(html_str);
            $.each(data, function( index, value ) {
                html_str='<option value="'+value.id+'" >'+value.title+'</option>';
                $('#'+child_el_id).append(html_str);
            });

            depend_element_ids.forEach(function(){
                $('#'+depend_element_ids).empty();
            });

            $('#'+master_el_id).prop('disabled', false);
            //$('#'+loading_gif_id).css('display', 'none');
        },
        error: function(data){
            alert(data.responseText);
            alert('دریافت اطلاعات با خطا مواجه شد!');
            $('#'+master_el_id).prop('disabled', false);
            //$('#'+loading_gif_id).css('display', 'none');
        }
    });

}




function toggleRegionCard(obj){
	if($(obj).find('.region-card-checkbox').prop('checked')==true){
		$(obj).removeClass('checked');
		$(obj).find('.region-card-checkbox').prop('checked',false);
	}else{
		$(obj).addClass('checked');
		$(obj).find('.region-card-checkbox').prop('checked',true);
		
	}
}
</script>

@endsection

resources/views/panel/admin/users/edit.blade.php
@extends('panel.layout.master')
@section('main_content')

    <div class="row mb-md-5">

        <div class="col-lg-12 margin-tb">

            <div class="pull-right">

                <h2>ویرایش کاربر</h2>

            </div>

            <div class="pull-left">

                <a class="btn btn-primary" href="{{ route('users.index') }}"> بازگشت</a>

            </div>

        </div>

    </div>


    @if (count($errors) > 0)

        <div class="alert alert-danger">

            <strong>خطا!</strong> در مقادیر ورودی ایراداتی وجود دارد.<br><br>

            <ul>

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif


    {!! Form::model($user, ['method' => 'PATCH','route' => ['users.update', $user->id]]) !!}

    <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>نام و نام خانوادگی:</strong>

                {!! Form::text('name', null, array('placeholder' => '','class' => 'form-control')) !!}

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>ایمیل:</strong>

                {!! Form::text('email', null, array('placeholder' => '','class' => 'form-control')) !!}

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>نوع کاربر:</strong>

                {!! Form::select('user_type', ['ADMIN'=>'ADMIN','CSO'=>'CSO','SALES_MANAGER'=>'SALES_MANAGER','SALES_SPECIALIST'=>'SALES_SPECIALIST','SALES_ACCOUNTANT'=>'SALES_ACCOUNTANT',
                'STOCK'=>'STOCK','DRIVER'=>'DRIVER'],$user->user_type, array('class' => 'form-control')) !!}

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>رمز عبور:</strong>

                {!! Form::password('password', array('placeholder' => '','class' => 'form-control')) !!}

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>تکرار رمز عبور:</strong>

                {!! Form::password('confirm-password', array('placeholder' => '','class' => 'form-control')) !!}

            </div>

        </div>

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>نقش:</strong>

                {!! Form::select('roles[]', $roles,$userRole, array('class' => 'form-control','multiple')) !!}

            </div>

        </div>
		
		<div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>شماره VOIP:</strong>

                {!! Form::text('voip_id', null, array('placeholder' => '','class' => 'form-control')) !!}

            </div>

        </div>
		
		
		<div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>وضعیت:</strong>

                {!! Form::select('is_active', ['1'=>'فعال','0'=>'غیرفعال'],$user->is_active, array('class' => 'form-control')) !!}

            </div>

        </div>


        <div class="col-xs-12 col-sm-12 col-md-12 text-center">

            <button type="submit" class="btn btn-primary">ثبت</button>

        </div>

    </div>

    {!! Form::close() !!}



@endsection

resources/views/panel/admin/users/index.blade.php
@extends('panel.layout.master')
@section('main_content')
    <div class="row mb-md-5">

        <div class="col-lg-12 margin-tb">

            <div class="pull-right">

                <h2>مدیریت کاربران</h2>

            </div>

            <div class="pull-left">

                <a class="btn btn-success" href="{{ route('users.create') }}"> ایجاد کاربر جدید</a>

            </div>

        </div>

    </div>


    @if ($message = Session::get('success'))

        <div class="alert alert-success">

            <p>{{ $message }}</p>

        </div>

    @endif


    <table class="table table-bordered">

        <tr>

            <th>ردیف</th>

            <th>نام و نام خانوادگی</th>

            <th>ایمیل</th>

            <th>نقش</th>
            <th>نوع کاربر</th>

            <th width="280px">عملیات</th>

        </tr>

        @foreach ($data as $key => $user)

            <tr>

                <td>{{ ++$i }}</td>

                <td>{{ $user->name }}</td>

                <td>{{ $user->email }}</td>

                <td>

                    @if(!empty($user->getRoleNames()))

                        @foreach($user->getRoleNames() as $v)

                            <label class="badge badge-success">{{ $v }}</label>

                        @endforeach

                    @endif

                </td>


                <td>{{ $user->user_type }}</td>

                <td>

                    <a class="btn btn-info" href="{{ route('users.show',$user->id) }}">نمایش</a>

		     @can('user-edit')
                    <a class="btn btn-primary" href="{{ route('users.edit',$user->id) }}">ویرایش</a>
                    @endcan

	             @can('user-delete')
                    {!! Form::open(['method' => 'DELETE','route' => ['users.destroy', $user->id],'style'=>'display:inline']) !!}
	             
                    {!! Form::submit('حذف', ['class' => 'btn btn-danger']) !!}

                    {!! Form::close() !!}
                    @endcan

                </td>

            </tr>

        @endforeach

    </table>


    {!! $data->links() !!}



@endsection