routes/web.php
	Route::get('campaigns/{campaign_id}/report', [\App\Http\Controllers\Admin\CampaignController::class, 'showCampaignReport'])->name('campaigns.showCampaignsReport');
	Route::resource('campaigns', \App\Http\Controllers\Admin\CampaignController::class);
	
	
    Route::resource('products', \App\Http\Controllers\Admin\ProductController::class);

	Route::get('business/{business_id}/cartable', [\App\Http\Controllers\Admin\BusinessController::class, 'showCartable'])->name('businesses.showCartable');
	
	
	Route::get('business/brands/edit/{business_id}', [\App\Http\Controllers\Admin\BrandController::class, 'editBusinessBrands'])->name('brands.editBusinessBrands');
	Route::patch('business/brands/update', [\App\Http\Controllers\Admin\BrandController::class, 'updateBusinessBrands'])->name('brands.updateBusinessBrands');
	
	
	//Route::get('business/brands/show/{business_id}', [\App\Http\Controllers\Admin\BrandController::class, 'showBusinessBrands'])->name('brands.showBusinessBrands');
	
	
	Route::resource('brands', \App\Http\Controllers\Admin\BrandController::class);
	
	Route::resource('proceedings', \App\Http\Controllers\Admin\ProceedingController::class);
	
	Route::resource('marketing', \App\Http\Controllers\Admin\MarketingController::class);
    
	Route::get('configs/edit', [\App\Http\Controllers\Admin\ConfigController::class, 'edit'])->name('configs.edit');
    Route::post('configs/update', [\App\Http\Controllers\Admin\ConfigController::class, 'update'])->name('configs.update');
    
	Route::get('teams/members/{team_id}', [\App\Http\Controllers\Admin\TeamController::class, 'createTeamMembers'])->name('teams.show-createTeamMembers-form');
	Route::post('teams/members/store-team-members', [\App\Http\Controllers\Admin\TeamController::class, 'storeTeamMembers'])->name('teams.store-team-members');
    
	Route::get('teams/report/{team_id}', [\App\Http\Controllers\Admin\TeamController::class, 'showTeamReport'])->name('teams.show-team-report'); 
	
    Route::resource('teams', \App\Http\Controllers\Admin\TeamController::class);
	
	Route::get('businesses/report', [\App\Http\Controllers\Admin\BusinessController::class, 'showBusinessesReport'])->name('businesses.showBusinessesReport');

    Route::resource('businesses', \App\Http\Controllers\Admin\BusinessController::class);
    
    Route::post('businesses/add-new-note', [\App\Http\Controllers\Admin\BusinessController::class, 'addNewNote'])->name('businesses.addNewNote');
    
    Route::get('accountant/business/approve/{business_id}', [\App\Http\Controllers\Admin\BusinessController::class, 'showAccountantApprovingForm'])->name('business.show-accounting-approving-form');
    
    Route::post('accountant/business/approve/{business_id}', [\App\Http\Controllers\Admin\BusinessController::class, 'accountantApprovingBusiness'])->name('business.accounting-approving-business');
    
    Route::get('sales-specialist/business/approve/{business_id}', [\App\Http\Controllers\Admin\BusinessController::class, 'showSalesSpecialistApprovingForm'])->name('business.show-sales-specialist-approving-form');
    
    Route::post('sales-specialist/business/approve/{business_id}', [\App\Http\Controllers\Admin\BusinessController::class, 'salesSpecialistApprovingBusiness'])->name('business.sales-specialist-approving-business');

    Route::resource('cities', \App\Http\Controllers\Admin\CityController::class);


    Route::get('comments/report', [\App\Http\Controllers\Admin\CommentController::class, 'showCommentsReport'])->name('comments.showCommentsReport');

    Route::resource('comments', \App\Http\Controllers\Admin\CommentController::class);
    
    
    Route::get('customers/{customer_id}/cartable', [\App\Http\Controllers\Admin\CustomerController::class, 'showCartable'])->name('customers.showCartable');
   
	Route::get('customers/report', [\App\Http\Controllers\Admin\CustomerController::class, 'showCustomersReport'])->name('customers.showCustomersReport');

    Route::resource('customers', \App\Http\Controllers\Admin\CustomerController::class);
    
    

    Route::get('sms/history', [\App\Http\Controllers\Admin\SmsController::class, 'history'])->name('sms.history');
    Route::get('sms/send/send-specialist-info', [\App\Http\Controllers\Admin\SmsController::class, 'sendSpecialistInfo'])->name('sms.sendSpecialistInfo');
    Route::get('sms/send', [\App\Http\Controllers\Admin\SmsController::class, 'showSendForm'])->name('sms.showSendForm');
    Route::post('sms/send', [\App\Http\Controllers\Admin\SmsController::class, 'sendSMS'])->name('sms.sendSMS');
    
    //Route::resource('sms', \App\Http\Controllers\Admin\SmsController::class);
    
    Route::post('customers/upload-excel-file', [\App\Http\Controllers\Admin\CustomerController::class, 'uploadExcelFile'])->name('customers.uploadExcelFile');
    
    Route::post('customers/update-customer-description', [\App\Http\Controllers\Admin\CustomerController::class, 'updateCustomerDescription'])->name('customers.updateCustomerDescription');
    Route::post('customers/add-new-note', [\App\Http\Controllers\Admin\CustomerController::class, 'addNewNote'])->name('customers.addNewNote');
	
	


    
    
    
    
    //unofficial
    Route::get('invoices/unofficial/get-pdf', [\App\Http\Controllers\Admin\UnofficialInvoiceController::class, 'getPdf'])->name('invoices.unofficial.get-pdf');

    Route::resource('invoices/unofficial', \App\Http\Controllers\Admin\UnofficialInvoiceController::class, ['as' => 'invoices']);
    
    Route::get('accountant/invoices/unofficial/primary/index', [\App\Http\Controllers\Admin\UnofficialInvoiceController::class, 'primaryInvoices'])->name('invoices.unofficial.show-primary-invoices');
    
    Route::get('accountant/invoices/unofficial/rejected/index', [\App\Http\Controllers\Admin\UnofficialInvoiceController::class, 'rejectedInvoices'])->name('invoices.unofficial.show-rejected-invoices');
    
    Route::get('accountant/invoices/unofficial/approve/{invoice_id}', [\App\Http\Controllers\Admin\UnofficialInvoiceController::class, 'showAccountantApprovingForm'])->name('invoices.unofficial.show-accounting-approving-form');
    
    Route::post('accountant/invoices/unofficial/approve/{invoice_id}', [\App\Http\Controllers\Admin\UnofficialInvoiceController::class, 'accountantApprovingInvoice'])->name('invoices.unofficial.accounting-approving-invoice');
    
    Route::get('sales-specialist/invoices/unofficial/approve/{invoice_id}', [\App\Http\Controllers\Admin\UnofficialInvoiceController::class, 'showSalesSpecialistApprovingForm'])->name('invoices.unofficial.show-sales-specialist-approving-form');
    
    Route::post('sales-specialist/invoices/unofficial/approve/{invoice_id}', [\App\Http\Controllers\Admin\UnofficialInvoiceController::class, 'salesSpecialistApprovingInvoice'])->name('invoices.unofficial.sales-specialist-approving-invoice');
    
 
    //returned invoices
    Route::get('invoices/returned/get-pdf', [\App\Http\Controllers\Admin\ReturnedInvoiceController::class, 'getPdf'])->name('invoices.returned.get-pdf');

    Route::resource('invoices/returned', \App\Http\Controllers\Admin\ReturnedInvoiceController::class, ['as' => 'invoices']);
    
    Route::get('accountant/invoices/returned/primary/index', [\App\Http\Controllers\Admin\ReturnedInvoiceController::class, 'primaryInvoices'])->name('invoices.returned.show-primary-invoices');
    
    Route::get('accountant/invoices/returned/rejected/index', [\App\Http\Controllers\Admin\ReturnedInvoiceController::class, 'rejectedInvoices'])->name('invoices.returned.show-rejected-invoices');
    
    Route::get('accountant/invoices/returned/approve/{invoice_id}', [\App\Http\Controllers\Admin\ReturnedInvoiceController::class, 'showAccountantApprovingForm'])->name('invoices.returned.show-accounting-approving-form');
    
    Route::post('accountant/invoices/returned/approve/{invoice_id}', [\App\Http\Controllers\Admin\ReturnedInvoiceController::class, 'accountantApprovingInvoice'])->name('invoices.returned.accounting-approving-invoice');
    
    Route::get('sales-specialist/invoices/returned/approve/{invoice_id}', [\App\Http\Controllers\Admin\ReturnedInvoiceController::class, 'showSalesSpecialistApprovingForm'])->name('invoices.returned.show-sales-specialist-approving-form');
    
    Route::post('sales-specialist/invoices/returned/approve/{invoice_id}', [\App\Http\Controllers\Admin\ReturnedInvoiceController::class, 'salesSpecialistApprovingInvoice'])->name('invoices.returned.sales-specialist-approving-invoice');
    
    
    //officials
    Route::get('invoices/get-pdf', [\App\Http\Controllers\Admin\InvoiceController::class, 'getPdf'])->name('invoices.get-pdf');

    Route::resource('invoices', \App\Http\Controllers\Admin\InvoiceController::class);
	
	Route::get('instances/get-pdf', [\App\Http\Controllers\Admin\InstanceController::class, 'getPdf'])->name('instances.get-pdf');
	
	Route::resource('instances', \App\Http\Controllers\Admin\InstanceController::class);
    
    Route::get('accountant/invoices/primary/index', [\App\Http\Controllers\Admin\InvoiceController::class, 'primaryInvoices'])->name('invoices.show-primary-invoices');
    
    Route::get('accountant/invoices/bijak/{bijak_id}/show', [\App\Http\Controllers\Admin\InvoiceController::class, 'showBijak'])->name('invoices.show-bijak');
    
    Route::get('accountant/invoices/bijak/show-create-form/{invoice_id}', [\App\Http\Controllers\Admin\InvoiceController::class, 'showCreateBijakform'])->name('invoices.show-create-bijak-form');
    
    Route::post('accountant/invoices/bijak/upload', [\App\Http\Controllers\Admin\InvoiceController::class, 'uploadBijak'])->name('invoices.upload-bijak');
    
    Route::get('accountant/invoices/rejected/index', [\App\Http\Controllers\Admin\InvoiceController::class, 'rejectedInvoices'])->name('invoices.show-rejected-invoices');
    

resources/views/panel/admin/comments/create.blade.php
@extends('panel.layout.master')
@section('main_content')

    <div class="row mb-md-5">

        <div class="col-lg-12 margin-tb">

            <div class="pull-right">

                <h2>ایجاد شکایت/پیشنهاد جدید</h2>

            </div>

            <div class="pull-left">

                <a class="btn btn-primary" href="{{ route('comments.index') }}"> بازگشت</a>

            </div>

        </div>

    </div>


    @if (count($errors) > 0)

        <div class="alert alert-danger">

            <strong>خطا!</strong> در مقادیر ورودی ایراداتی وجود دارد.<br><br>

            <ul>

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif



    {!! Form::open(array('route' => 'comments.store','method'=>'POST')) !!}

    <div class="row mb-5">
    
    
	<div class="col-xs-12 col-sm-12 col-md-4">

		<div class="form-group">

		<strong>دسته بندی:</strong>

			<select  name='comment_category_id' id='comment_category_id' class='form-control pull-right' >
				@foreach($commentCategories as $category)
				<option @if(old('comment_category_id')==$category->id) selected @endif value="{{$category->id}}" >{{$category->category_text}}</option>
				@endforeach
				
			</select>

		</div>

	</div>
    

        <div class="col-xs-12 col-sm-12 col-md-4">

            <div class="form-group">

                <strong>شناسه مشتری:</strong>
                
                <input type="number" name="customer_id" id="customer_id" value="{{old('customer_id')}}" class="form-control" placeholder="" onKeyPress="return NumbersOnly(event, 'customer_id')">

            </div>

        </div>
        
	<div class="col-xs-12 col-sm-12 col-md-4">

		<div class="form-group">

		<strong>تلفن تماس:</strong>

		{!! Form::text('customer_phone', old('customer_phone'), array('placeholder' => '','class' => 'form-control')) !!}

		</div>
	</div>

        
        
	<div class="col-xs-12 col-sm-12 col-md-12 mt-md-2">

		<div class="form-group">

			<strong>متن شکایت/پیشنهاد:</strong>

			<textarea class="form-control" rows="10" name="comment_text" placeholder="" >{{old('comment_text')}}</textarea>

		</div>

	</div>

        
        
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">

            <button type="submit" class="btn btn-primary">ثبت</button>

        </div>

    </div>

    {!! Form::close() !!}




@endsection

@section('additional_js_bottom')
<script>
    function NumbersOnly(evt, label) {
        var status = document.getElementById(label);
        evt = (evt) ? evt : window.event;
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if (charCode == 46) {
            return true;
        }
        if (charCode < 48 || charCode > 57) {
            status.innerHTML = 'Numbers Only Please';
            return false;
        }
        status.innerHTML = '';
        return true;
    }
</script>
@endsection

resources/views/panel/admin/comments/edit.blade.php
@extends('panel.layout.master')
@section('main_content')

    <div class="row">

        <div class="col-lg-12 margin-tb">

            <div class="pull-right">

                <h2>ویرایش شکایت/پیشنهاد</h2>

            </div>

            <div class="pull-left">

                <a class="btn btn-primary" href="{{ route('comments.index') }}"> بازگشت</a>

            </div>

        </div>

    </div>


    @if ($errors->any())

        <div class="alert alert-danger">

            <strong>خطا!</strong> در مقادیر ورودی ایراداتی وجود دارد.<br><br>

            <ul>

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif


    <form action="{{ route('comments.update',$comment->id) }}" method="POST">

        @csrf

        @method('PUT')


        <div class="row">
        
        
        	<div class="col-xs-12 col-sm-12 col-md-4">

		<div class="form-group">

		<strong>دسته بندی:</strong>

			<select  name='comment_category_id' id='comment_category_id' class='form-control pull-right' >
				@foreach($commentCategories as $category)
				<option @if(old('comment_category_id', isset($comment->comment_category_id) ? $comment->comment_category_id : '')==$category->id) selected @endif value="{{$category->id}}" >{{$category->category_text}}</option>
				@endforeach
				
			</select>

		</div>

	</div>
    

        <div class="col-xs-12 col-sm-12 col-md-4">

            <div class="form-group">

                <strong>شناسه مشتری:</strong>
                
                <input type="number" name="customer_id" id="customer_id" value="{{old('customer_id',$comment->customer_id)}}" class="form-control" placeholder="" onKeyPress="return NumbersOnly(event, 'customer_id')">

            </div>

        </div>
        
	<div class="col-xs-12 col-sm-12 col-md-4">

		<div class="form-group">

		<strong>تلفن تماس:</strong>

		{!! Form::text('customer_phone', old('customer_phone',$comment->customer_phone), array('placeholder' => '','class' => 'form-control')) !!}

		</div>
	</div>

        
        
	<div class="col-xs-12 col-sm-12 col-md-12 mt-md-2">

		<div class="form-group">

			<strong>متن شکایت/پیشنهاد:</strong>

			<textarea class="form-control" rows="10" name="comment_text" placeholder="" >{{old('comment_text',$comment->comment_text)}}</textarea>

		</div>

	</div>
        
        
        
        
        
        
        
        
            <div class="col-xs-12 col-sm-12 col-md-12 text-center">

                <button type="submit" class="btn btn-primary">ثبت تغییرات</button>

            </div>

        </div>


    </form>



@endsection


@section('additional_js_bottom')
<script>
    function NumbersOnly(evt, label) {
        var status = document.getElementById(label);
        evt = (evt) ? evt : window.event;
        var charCode = (evt.which) ? evt.which : evt.keyCode;
        if (charCode == 46) {
            return true;
        }
        if (charCode < 48 || charCode > 57) {
            status.innerHTML = 'Numbers Only Please';
            return false;
        }
        status.innerHTML = '';
        return true;
    }
</script>
@endsection

resources/views/panel/admin/comments/index.blade.php
@extends('panel.layout.master')
@section('main_content')
    <div class="row mb-md-5">

        <div class="col-lg-12 margin-tb">

            <div class="pull-right">

                <h2>مدیریت شکایات و پیشنهادات</h2>

            </div>

            <div class="pull-left">

                <a class="btn btn-success" href="{{ route('comments.create') }}"> اضافه کردن شکایت/پیشنهاد</a>

            </div>

        </div>

    </div>


    @if ($message = Session::get('success'))

        <div class="alert alert-success">

            <p>{{ $message }}</p>

        </div>

    @endif
    
    @if ($message = Session::get('danger'))

        <div class="alert alert-danger">

            <p>{{ $message }}</p>

        </div>

    @endif


    <table class="table table-bordered">

        <tr>

            <th>ردیف</th>

            <th>دسته بندی</th>
            <th>مشتری</th>
            <th>شماره تماس</th>
            
            <th width="280px">عملیات</th>

        </tr>

        @foreach ($data as $key => $comment)

            <tr>

                <td>{{ ++$i }}</td>

                <td>{{ $comment->category()->first()->category_text }}</td>

                <td><a href="{{ !empty($comment->customer_id)?route('customers.edit',$comment->customer()->first()->id):'#' }}" target="_blank">{{ !empty($comment->customer_id)?$comment->customer()->first()->business_name:'-' }}</a></td>
                <td>{{ $comment->customer_phone }}</td>
              
		
                <td>
                
		     

                    <a class="btn btn-info" href="{{ route('comments.show',$comment->id) }}">نمایش</a>

                    <a class="btn btn-primary" href="{{ route('comments.edit',$comment->id) }}">ویرایش</a>

                    {!! Form::open(['method' => 'DELETE','route' => ['comments.destroy', $comment->id],'style'=>'display:inline']) !!}

                    {!! Form::submit('حذف', ['class' => 'btn btn-danger']) !!}

                    {!! Form::close() !!}

                </td>

            </tr>

        @endforeach

    </table>


    {!! $data->render() !!}



@endsection

resources/views/panel/admin/comments/report.blade.php
@extends('panel.layout.master')
@section('additional_js_top2')

<script src="{{asset('highcharts/highcharts.js')}}"></script>
<script src="{{asset('highcharts/modules/exporting.js')}}"></script>
<script src="{{asset('highcharts/modules/export-data.js')}}"></script>
<script src="{{asset('highcharts/modules/accessibility.js')}}"></script>

@endsection
@section('main_content')
    <div class="row mb-md-5">

        <div class="col-lg-12 margin-tb">

            <div class="pull-right">

                <h2>گزارش جامع شکایات و پیشنهادات</h2>

            </div>

           

        </div>

    </div>


    @if ($message = Session::get('success'))

        <div class="alert alert-success">

            <p>{{ $message }}</p>

        </div>

    @endif
    
    @if ($message = Session::get('danger'))

        <div class="alert alert-danger">

            <p>{{ $message }}</p>

        </div>

    @endif
    
    
    
    <div class="row">    
    <div class="col-lg-12 mb-md-5">
        <form action="{{route('comments.showCommentsReport')}}" method="GET">
        <div class="row">
	    
            
            
            
            <div class="col-xs-12 col-sm-12 col-md-2 form-input-container">

                <div class="form-group">

                    <strong>دسته بندی:</strong>
 
                    <select  name='comment_category_id' id='comment_category_id' class='form-control pull-right'>
                        <option {{(!old('comment_category_id', isset(request()->comment_category_id) ? request()->comment_category_id : '')? 'selected' : '')}} value="">همه دسته بندیها</option>
                        @foreach($commentCategories as $commentCategory)
                            <option @if(old('comment_category_id', isset(request()->comment_category_id) ? request()->comment_category_id : '')==$commentCategory->id) selected @endif value="{{$commentCategory->id}}" >{{$commentCategory->category_text}}</option>
                        @endforeach
                    </select>

                </div>

            </div>
            
            
            <div class="col-xs-12 col-sm-12 col-md-2 form-input-container">

                <div class="form-group">

                    <strong>از تاریخ:</strong>

                    <input data-jdp type="text" name="from_date" id="from_date" value="{{ old('from_date',request()->from_date) }}" class="form-control" placeholder="">

                </div>

            </div>
            
            
            <div class="col-xs-12 col-sm-12 col-md-2 form-input-container">

                <div class="form-group">

                    <strong>تا تاریخ:</strong>
                    
                    <input data-jdp type="text" name="to_date" id="to_date" value="{{ old('to_date',request()->to_date) }}" class="form-control" placeholder="">

                </div>

            </div>
            
            
            <div class="col-xs-12 col-sm-12 col-md-2 form-input-container">

                <div class="form-group">

                    <strong>بازه زمانی:</strong>

                    <select  name='report_period' id='report_period' class='form-control pull-right' autocomplete='off'>
                    	<option @if(old('report_period', isset(request()->report_period) ? request()->report_period : '')==2) selected @endif value="2" >ماهانه</option>
                    	 <option @if(old('report_period', isset(request()->report_period) ? request()->report_period : '')==1) selected @endif value="1" >روزانه</option>
                    </select>

                </div>

            </div>
            
	
        </div>
        
        <div class="row">
		<div class="col-xs-12 col-sm-12 col-md-12 form-input-container">
			<div class="pull-left">
			<button type="submit" class="btn btn-success">دریافت گزارش</button>
			</div>
		</div>
        </div>
        </form>
    </div>
</div>


  
<div class="row mt-5">   
    <div class="col-lg-12 mb-md-5">
    	<h4>نمودار بر اساس زمان</h4>
    </div> 
    <div class="col-lg-12 mb-md-5">
	<figure class="highcharts-figure">
		<div id="container"></div>
		
	</figure>
   </div>
</div>


<div class="row mt-5">   
    <div class="col-lg-12 mb-md-5">
    	<h4>نمودار بر اساس دسته بندی</h4> 
    </div> 
    <div class="col-lg-12 mb-md-5">
    	<figure class="highcharts-figure">
		<div id="container2"></div>
		
	</figure>
   </div>
</div>

@endsection

@section('additional_js_bottom')

<script type="text/javascript">
Highcharts.chart('container', {
    chart: {
        type: 'column'
    },
    title: {
        text: 'نمودار تعداد شکایات و پیشنهادات'
    },
    xAxis: {
        categories: [
        		"تاریخ"
        		],
        crosshair: true
    },
    yAxis: {
        min: 0,
        title: {
            text: 'تعداد شکایات و پیشنهادات'
        }
    },
    tooltip: {
        useHTML: true
    },
    plotOptions: {
        column: {
            pointPadding: 0.2,
            borderWidth: 0
        }
    },
    series: [
    
    	@foreach($chart1DataArray as $key=>$chartData)
    		{
    			name: '{{$key}}',
    			data: [{{$chartData}}]
    		}
    		@if($key!=array_key_last($chart1DataArray))
    		,
    		@endif
    	@endforeach
    
    ]
});


Highcharts.chart('container2', {
    chart: {
        type: 'column'
    },
    title: {
        text: 'نمودار تعداد شکایات و پیشنهادات بر اساس دسته بندی'
    },
    xAxis: {
        categories: [
        		"دسته بندی"
        		],
        crosshair: true
    },
    yAxis: {
        min: 0,
        title: {
            text: 'تعداد شکایات و پیشنهادات'
        }
    },
    tooltip: {
        useHTML: true
    },
    plotOptions: {
        column: {
            pointPadding: 0.2,
            borderWidth: 0
        }
    },
    series: [
    
    	@foreach($chart2DataArray as $key=>$chartData)
    		{
    			name: '{{$key}}',
    			data: [{{$chartData}}]
    		}
    		@if($key!=array_key_last($chart2DataArray))
    		,
    		@endif
    	@endforeach
    
    ]
});
</script>

@endsection

resources/views/panel/admin/comments/show.blade.php
@extends('panel.layout.master')
@section('main_content')

    <div class="row mb-md-5">

        <div class="col-lg-12 margin-tb">

            <div class="pull-right">

                <h2> نمایش جزئیات شکایت/پیشنهاد</h2>

            </div>

            <div class="pull-left">

                <a class="btn btn-primary" href="{{ route('customers.index') }}"> بازگشت</a>

            </div>

        </div>

    </div>


    <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>مشتری:</strong>

                <a href="{{ !empty($comment->customer_id)?route('customers.edit',$comment->customer()->first()->id):'#' }}" target="_blank">{{ !empty($comment->customer_id)?$comment->customer()->first()->business_name:'-' }}</a>

            </div>

        </div>


        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>دسته بندی:</strong>

                {{ $comment->category()->first()->category_text }}

            </div>

        </div>


        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>متن شکایت/پیشنهاد:</strong>

                {{ $comment->comment_text }}

            </div>

        </div>


        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>شماره تماس:</strong>

                {{ $comment->customer_phone }}

            </div>

        </div>


        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>کاربر ایجاد کننده:</strong>

                {{ $comment->creator()->first()->name }}({{ $comment->creator()->first()->email }})

            </div>

        </div>


        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>تاریخ و زمان ایجاد:</strong>

                {{ $comment->created_at }}

            </div>

        </div>


        <div class="col-xs-12 col-sm-12 col-md-12">

            <div class="form-group">

                <strong>تاریخ و زمان آخرین ویرایش:</strong>

                {{ $comment->updated_at }}

            </div>

        </div>

    </div>

@endsection