routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::group(['middleware'=>['auth']],function() {
    Route::get('/', function () {
        return view('panel.pages.dashboard');
    })->name('showDashboard');
});
*/

Route::group(['middleware'=>['auth','init_shared_data']],function() {
	Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('showDashboard');
});

Auth::routes(['register' => false]);

Route::group(['middleware'=>['auth','init_shared_data']],function() {
	Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
});


Route::get('products/update-all', [\App\Http\Controllers\Admin\ProductController::class, 'updateAllProducts'])->name('products.updateAllProducts');

Route::get('customers/update-all', [\App\Http\Controllers\Admin\CustomerController::class, 'updateAllCustomers'])->name('customers.updateAllCustomers');


Route::group(['middleware' => ['auth', 'init_shared_data']], function() {
	
	
	Route::get('users/toggle-walking-status', [\App\Http\Controllers\Admin\UserController::class, 'toggleWalkingStatus'])->name('users.toggleWalkingStatus');
	
	Route::get('users/{user_id}/geo-update', [\App\Http\Controllers\Admin\UserController::class, 'updateGeoPath'])->name('users.updateGeoPath');
	Route::get('users/{user_id}/walked-paths', [\App\Http\Controllers\Admin\UserController::class, 'showUserWalkedPaths'])->name('users.showUserWalkedPaths');
	
	Route::get('users/{path_id}/show-walked-path', [\App\Http\Controllers\Admin\UserController::class, 'showWalkedPath'])->name('users.showWalkedPath');
	
	
	Route::get('clues/report', [\App\Http\Controllers\Admin\ClueController::class, 'showCluesReport'])->name('clues.showCluesReport');
	
	Route::post('clues/merge', [\App\Http\Controllers\Admin\ClueController::class, 'mergeToAnotherClue'])->name('clues.merge');
	
	Route::post('clues/merge/confirm', [\App\Http\Controllers\Admin\ClueController::class, 'mergeConfirmToAnotherClue'])->name('clues.merge.confirm');
	
	Route::get('clues/{clue_id}/cartable', [\App\Http\Controllers\Admin\ClueController::class, 'showCartable'])->name('clues.showCartable');
	Route::post('clues/add-new-note', [\App\Http\Controllers\Admin\ClueController::class, 'addNewNote'])->name('clues.addNewNote');
	Route::post('clues/add-new-report-process', [\App\Http\Controllers\Admin\ClueController::class, 'addNewReportProcess'])->name('clues.addNewReportProcess');
	Route::post('clues/update-clue-customer-status', [\App\Http\Controllers\Admin\ClueController::class, 'updateClueCustomerStatus'])->name('clues.updateClueCustomerStatus');
	Route::post('clues/update-clue-business-status', [\App\Http\Controllers\Admin\ClueController::class, 'updateClueBusinessStatus'])->name('clues.updateClueBusinessStatus');
	Route::post('clues/update-clue-pre-invoice-status', [\App\Http\Controllers\Admin\ClueController::class, 'updateCluePreInvoiceStatus'])->name('clues.updateCluePreInvoiceStatus');
	Route::post('clues/update-clue-invoice-status', [\App\Http\Controllers\Admin\ClueController::class, 'updateClueInvoiceStatus'])->name('clues.updateClueInvoiceStatus');
	
	
	Route::post('clues/update-clue-description', [\App\Http\Controllers\Admin\ClueController::class, 'updateClueDescription'])->name('clues.updateClueDescription');
	
	
	Route::post('clues/update-clue-products', [\App\Http\Controllers\Admin\ClueController::class, 'updateClueProducts'])->name('clues.updateClueProducts');
	
	Route::post('clues/update-clue-marketing-list', [\App\Http\Controllers\Admin\ClueController::class, 'updateClueMarketingList'])->name('clues.updateClueMarketingList');
	
	
	
	
	Route::resource('clues', \App\Http\Controllers\Admin\ClueController::class);
	
	
	Route::get('competitors/report', [\App\Http\Controllers\Admin\CompetitorController::class, 'showCompetitorsReport'])->name('competitors.showCompetitorsReport');
	
	Route::resource('competitors', \App\Http\Controllers\Admin\CompetitorController::class);
	
	 
	

    Route::resource('roles', \App\Http\Controllers\Admin\RoleController::class);
    
    Route::get('users/cities/edit/{user_id}', [\App\Http\Controllers\Admin\UserController::class, 'editUserCities'])->name('users.edit-user-cities');
    Route::get('users/cities/add', [\App\Http\Controllers\Admin\UserController::class, 'addCityToUser'])->name('users.add-city-to-user');
    Route::delete('users/cities/remove', [\App\Http\Controllers\Admin\UserController::class, 'removeUserCity'])->name('users.remove-user-city');
    Route::delete('users/cities/remove-mass', [\App\Http\Controllers\Admin\UserController::class, 'removeUserCityMass'])->name('users.remove-user-city-mass');

    Route::resource('users', \App\Http\Controllers\Admin\UserController::class);
    
    
	Route::get('campaigns/{campaign_id}/report', [\App\Http\Controllers\Admin\CampaignController::class, 'showCampaignReport'])->name('campaigns.showCampaignsReport');
	Route::resource('campaigns', \App\Http\Controllers\Admin\CampaignController::class);
	
	
    Route::resource('products', \App\Http\Controllers\Admin\ProductController::class);

	Route::get('business/{business_id}/cartable', [\App\Http\Controllers\Admin\BusinessController::class, 'showCartable'])->name('businesses.showCartable');
	
	
	Route::get('business/brands/edit/{business_id}', [\App\Http\Controllers\Admin\BrandController::class, 'editBusinessBrands'])->name('brands.editBusinessBrands');
	Route::patch('business/brands/update', [\App\Http\Controllers\Admin\BrandController::class, 'updateBusinessBrands'])->name('brands.updateBusinessBrands');
	
	
	//Route::get('business/brands/show/{business_id}', [\App\Http\Controllers\Admin\BrandController::class, 'showBusinessBrands'])->name('brands.showBusinessBrands');
	
	
	Route::resource('brands', \App\Http\Controllers\Admin\BrandController::class);
	
	Route::resource('proceedings', \App\Http\Controllers\Admin\ProceedingController::class);
	
	Route::resource('marketing', \App\Http\Controllers\Admin\MarketingController::class);
    
	Route::get('configs/edit', [\App\Http\Controllers\Admin\ConfigController::class, 'edit'])->name('configs.edit');
    Route::post('configs/update', [\App\Http\Controllers\Admin\ConfigController::class, 'update'])->name('configs.update');
    
	Route::get('teams/members/{team_id}', [\App\Http\Controllers\Admin\TeamController::class, 'createTeamMembers'])->name('teams.show-createTeamMembers-form');
	Route::post('teams/members/store-team-members', [\App\Http\Controllers\Admin\TeamController::class, 'storeTeamMembers'])->name('teams.store-team-members');
    
	Route::get('teams/report/{team_id}', [\App\Http\Controllers\Admin\TeamController::class, 'showTeamReport'])->name('teams.show-team-report'); 
	
    Route::resource('teams', \App\Http\Controllers\Admin\TeamController::class);
	
	Route::get('businesses/report', [\App\Http\Controllers\Admin\BusinessController::class, 'showBusinessesReport'])->name('businesses.showBusinessesReport');

    Route::resource('businesses', \App\Http\Controllers\Admin\BusinessController::class);
    
    Route::post('businesses/add-new-note', [\App\Http\Controllers\Admin\BusinessController::class, 'addNewNote'])->name('businesses.addNewNote');
    
    Route::get('accountant/business/approve/{business_id}', [\App\Http\Controllers\Admin\BusinessController::class, 'showAccountantApprovingForm'])->name('business.show-accounting-approving-form');
    
    Route::post('accountant/business/approve/{business_id}', [\App\Http\Controllers\Admin\BusinessController::class, 'accountantApprovingBusiness'])->name('business.accounting-approving-business');
    
    Route::get('sales-specialist/business/approve/{business_id}', [\App\Http\Controllers\Admin\BusinessController::class, 'showSalesSpecialistApprovingForm'])->name('business.show-sales-specialist-approving-form');
    
    Route::post('sales-specialist/business/approve/{business_id}', [\App\Http\Controllers\Admin\BusinessController::class, 'salesSpecialistApprovingBusiness'])->name('business.sales-specialist-approving-business');

    Route::resource('cities', \App\Http\Controllers\Admin\CityController::class);


    Route::get('comments/report', [\App\Http\Controllers\Admin\CommentController::class, 'showCommentsReport'])->name('comments.showCommentsReport');

    Route::resource('comments', \App\Http\Controllers\Admin\CommentController::class);
    
    
    Route::get('customers/{customer_id}/cartable', [\App\Http\Controllers\Admin\CustomerController::class, 'showCartable'])->name('customers.showCartable');
   
	Route::get('customers/report', [\App\Http\Controllers\Admin\CustomerController::class, 'showCustomersReport'])->name('customers.showCustomersReport');

    Route::resource('customers', \App\Http\Controllers\Admin\CustomerController::class);
    
    

    Route::get('sms/history', [\App\Http\Controllers\Admin\SmsController::class, 'history'])->name('sms.history');
    Route::get('sms/send/send-specialist-info', [\App\Http\Controllers\Admin\SmsController::class, 'sendSpecialistInfo'])->name('sms.sendSpecialistInfo');
    Route::get('sms/send', [\App\Http\Controllers\Admin\SmsController::class, 'showSendForm'])->name('sms.showSendForm');
    Route::post('sms/send', [\App\Http\Controllers\Admin\SmsController::class, 'sendSMS'])->name('sms.sendSMS');
    
    //Route::resource('sms', \App\Http\Controllers\Admin\SmsController::class);
    
    Route::post('customers/upload-excel-file', [\App\Http\Controllers\Admin\CustomerController::class, 'uploadExcelFile'])->name('customers.uploadExcelFile');
    

app/Models/Business_type.php
<?php


namespace App\Models;


use Illuminate\Database\Eloquent\Factories\HasFactory;

use Illuminate\Database\Eloquent\Model;


class Business_type extends Model

{

    use HasFactory;


    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
     
     
    protected $table = "business_types";

    protected $fillable = [
    ];


    public function city()
    {
        return $this->hasMany(Business::class);
    }



}

resources/views/panel/admin/accountant/businesses/approve-by-sales-specialist.blade.php
@extends('panel.layout.master')
@section('main_content')

    <div class="row mb-md-5">

        <div class="col-lg-12 margin-tb">

            <div class="pull-right">

                <h2>تایید اطلاعات کسب و کار: 
                    {{$business->business_name}}
                </h2>

            </div>

            <div class="pull-left">

                <a class="btn btn-primary" href="{{ route('businesses.index') }}"> بازگشت</a>

            </div>

        </div>

    </div>


    @if (count($errors) > 0)

        <div class="alert alert-danger">

            <strong>خطا!</strong> در مقادیر ورودی ایراداتی وجود دارد.<br><br>

            <ul>

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif
    
    <div class="row mb-5">
    	<div class="col-xs-12 col-sm-12 col-md-12">
    		<a href="{{route('businesses.edit',$business->id)}}" target="_blank">مشاهده اطلاعات کسب و کار</a>
    	</div>
    </div>


    {!! Form::model($business, ['method' => 'POST','route' => ['business.sales-specialist-approving-business', $business->id]]) !!}


	<input type="hidden" name="business_id" value="{{$business->id}}">

    <div class="row">

	<div class="col-xs-12 col-sm-12 col-md-12 form-input-container">

		<div class="form-group">

		    <strong>توضیحات:</strong>

		    <textarea class="form-control" style="height:200px" name="sales_specialist_approving_description" placeholder="" required>{{ old('sales_specialist_approving_description',$business->sales_specialist_approving_description) }}</textarea>

		</div>

	</div>



        <div class="col-xs-12 col-sm-12 col-md-4">

            <div class="form-group">

                <strong>وضعیت:</strong>

                <select  name='approved_by_sales_specialist' id='approved_by_sales_specialist' class='form-control pull-right' >
                    <option @if(old('approved_by_sales_specialist', isset($business->approved_by_sales_specialist) ? $business->approved_by_sales_specialist : '')==1) selected @endif value="1" >تایید</option>
                    <option @if(old('approved_by_sales_specialist', isset($business->approved_by_sales_specialist) ? $business->approved_by_sales_specialist : '')==2) selected @endif value="2" >رد</option>
                </select>

            </div>

        </div>


        <div class="col-xs-12 col-sm-12 col-md-12 text-center">

            <button type="submit" class="btn btn-primary">ثبت</button>

        </div>

    </div>

    {!! Form::close() !!}



@endsection

resources/views/panel/admin/accountant/businesses/approve.blade.php
@extends('panel.layout.master')
@section('main_content')

    <div class="row mb-md-5">

        <div class="col-lg-12 margin-tb">

            <div class="pull-right">

                <h2>تایید اطلاعات کسب و کار: 
                    {{$business->business_name}}
                </h2>

            </div>

            <div class="pull-left">

                <a class="btn btn-primary" href="{{ route('businesses.index') }}"> بازگشت</a>

            </div>

        </div>

    </div>


    @if (count($errors) > 0)

        <div class="alert alert-danger">

            <strong>خطا!</strong> در مقادیر ورودی ایراداتی وجود دارد.<br><br>

            <ul>

                @foreach ($errors->all() as $error)

                    <li>{{ $error }}</li>

                @endforeach

            </ul>

        </div>

    @endif
	
	@if ($message = Session::get('danger'))

        <div class="alert alert-danger">

            <p>{{ $message }}</p>

        </div>

    @endif
    
    <div class="row mb-5">
    	<div class="col-xs-12 col-sm-12 col-md-12">
    		<a href="{{route('businesses.edit',$business->id)}}" target="_blank">مشاهده اطلاعات کسب و کار</a>
    	</div>
    </div>


    {!! Form::model($business, ['method' => 'POST','route' => ['business.accounting-approving-business', $business->id]]) !!}


	<input type="hidden" name="business_id" value="{{$business->id}}">

    <div class="row">

	<div class="col-xs-12 col-sm-12 col-md-12 form-input-container">

		<div class="form-group">

		    <strong>توضیحات:</strong>

		    <textarea class="form-control" style="height:200px" name="accountant_approving_description" placeholder="" required>{{ old('accountant_approving_description',$business->accountant_approving_description) }}</textarea>

		</div>

	</div>



        <div class="col-xs-12 col-sm-12 col-md-4">

            <div class="form-group">

                <strong>وضعیت:</strong>

                <select  name='approved_by_accountant' id='approved_by_accountant' class='form-control pull-right' >
                    <option @if(old('approved_by_accountant', isset($business->approved_by_accountant) ? $business->approved_by_accountant : '')==1) selected @endif value="1" >تایید</option>
                    <option @if(old('approved_by_accountant', isset($business->approved_by_accountant) ? $business->approved_by_accountant : '')==2) selected @endif value="2" >رد</option>
                </select>

            </div>

        </div>


        <div class="col-xs-12 col-sm-12 col-md-12 text-center">

            <button type="submit" class="btn btn-primary">ثبت</button>

        </div>

    </div>

    {!! Form::close() !!}



@endsection